import { Suspense } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import {
  TrendingUp,
  TrendingDown,
  IndianRupee,
  ShoppingCart,
  Users,
  Package,
  Plus,
  ArrowRight,
  AlertCircle,
  CheckCircle2,
} from 'lucide-react'
import Link from 'next/link'
import { RevenueChart } from '@/components/dashboard/RevenueChart'
// import { TopProductsCard } from '@/components/dashboard/TopProductsCard'
import {
  getDashboardStats,
  getRevenueChartData,
  getRecentOrders,
  getDashboardAlerts,
  getEnquiries,
  getTopProducts,
  getOnboardingChecklistData,
} from './action'
import { EnquiriesCard } from '@/components/dashboard/EnquiriesCard'
import { TopProductsCard } from '@/components/dashboard/TopProducts'
import { QuickActions } from '@/components/dashboard/QuickActions'
import { AlertsWidget } from '@/components/dashboard/AlertsWidget'
import { TodoWidget } from '@/components/dashboard/TodoWidget'
import { getTodos, getAutoGeneratedTodos } from './todo-actions'
import { WelcomeToast } from './DashboardClient'
import { VerificationBanner } from '@/components/dashboard/VerificationBanner'
import { getUserProfile } from './action'
import { StoreShareWidget } from '@/components/dashboard/StoreShareWidget'
import { OnboardingChecklistCard } from '@/components/dashboard/OnboardingChecklistCard'

export const metadata = {
  title: 'Dashboard - ResellerPro',
  description: 'Your business overview',
}

export default async function DashboardPage() {
  // Fetch all data in parallel for better performance
  const [stats, revenueData, recentOrders, alerts, enquiries, topProducts, todos, suggestions, profile, checklistData] = await Promise.all([
    getDashboardStats(),
    getRevenueChartData(),
    getRecentOrders(),
    getDashboardAlerts(),
    getEnquiries(),
    getTopProducts(),
    getTodos(),
    getAutoGeneratedTodos(),
    getUserProfile(),
    getOnboardingChecklistData().catch((err) => { console.error('Checklist fetch failed:', err); return null }),
  ])

  return (
    <div className="space-y-6">
      {profile && (
        <VerificationBanner
          email={profile.email}
          isVerified={profile.email_verified || false}
        />
      )}
      <WelcomeToast />

      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold tracking-tight mb-2">Dashboard</h1>
        <p className="text-muted-foreground text-[13px] sm:text-[15px]">
          Welcome back! Here's what's happening with your business today.
        </p>
      </div>

      {profile?.shop_slug && (
        <StoreShareWidget 
          shopSlug={profile.shop_slug} 
          storeStatus={profile.shop_theme?.storeStatus || 'open'} 
        />
      )}

      {/* Quick Stats */}
      <div className="grid gap-4 grid-cols-2 md:grid-cols-2 lg:grid-cols-2 text-nowrap">
        <StatsCard
          type="revenue"
          title="Today's Revenue"
          value={stats?.todayRevenue || 0}
          change={stats?.revenueChange || 0}
          icon={IndianRupee}
        />
        <StatsCard
          type="profit"
          title="Today's Profit"
          value={stats?.todayProfit || 0}
          change={stats?.profitChange || 0}
          icon={TrendingUp}
        />
      </div>

      {/* Enquiries Section */}
      <section>
        <EnquiriesCard enquiries={enquiries} />
      </section>

      {/* Quick Actions, Alerts & Daily Tasks */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <QuickActions />
        <AlertsWidget alerts={alerts} />
        <TodoWidget todos={todos} suggestions={suggestions} />
      </div>

      {/* Main Grid */}
      <div className="grid gap-4 lg:grid-cols-7">
        {/* Revenue Chart */}
        <Card className="lg:col-span-4 h-full">
          <CardHeader>
            <CardTitle>Revenue Overview</CardTitle>
            <CardDescription>Your revenue for the last 7 days</CardDescription>
          </CardHeader>
          <CardContent className="h-full">
            <div className="flex items-start justify-start w-full h-full rounded-lg">
              <div className="text-muted-foreground w-full h-full">
                <RevenueChart data={revenueData} />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Recent Activity */}
        <Card className="lg:col-span-3">
          <CardHeader>
            <CardTitle>Recent Orders</CardTitle>
            <CardDescription>Latest 5 orders from customers</CardDescription>
          </CardHeader>
          <CardContent>
            {recentOrders.length > 0 ? (
              <div className="space-y-4">
                {recentOrders.map((order) => (
                  <RecentOrderItem
                    key={order.id}
                    customer={order.customer}
                    amount={`₹${order.amount.toLocaleString('en-IN')}`}
                    product={order.product}
                    time={order.time}
                    status={order.status}
                  />
                ))}
              </div>
            ) : (
              <div className="text-center py-8 text-muted-foreground">
                <ShoppingCart className="h-12 w-12 mx-auto mb-2 opacity-50" />
                <p>No orders yet</p>
                <p className="text-sm">Create your first order to get started</p>
              </div>
            )}
            <Button variant="ghost" className="w-full mt-4" asChild>
              <Link href="/orders">
                View All Orders
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          </CardContent>
        </Card>
      </div>



      {/* Top Products */}
      {/* Top Products */}
      <TopProductsCard topProducts={topProducts} />

      {/* Floating Setup Guide — Stripe-style bottom-right widget */}
      {checklistData?.onboardingCompleted && (
        <OnboardingChecklistCard
          hasProducts={checklistData.hasProducts}
          shopSlug={checklistData.shopSlug}
          hasOrders={checklistData.hasOrders}
          hasCustomized={checklistData.hasCustomized || false}
        />
      )}
    </div>
  )
}

// Loading skeleton for top products
function TopProductsSkeleton() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Top Selling Products</CardTitle>
        <CardDescription>Best performers this month</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {[1, 2, 3, 4].map((i) => (
            <div key={i} className="flex items-center gap-4">
              <Skeleton className="h-12 w-12 rounded-lg" />
              <div className="flex-1 space-y-2">
                <Skeleton className="h-4 w-32" />
                <Skeleton className="h-3 w-48" />
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  )
}

function StatsCard({
  type,
  title,
  value,
  change,
  icon: Icon,
}: {
  type: 'revenue' | 'profit'
  title: string
  value: number
  change: number
  icon: React.ComponentType<{ className?: string }>
}) {
  const isPositive = change > 0
  const isNeutral = change === 0
  const formattedValue = `₹${value.toLocaleString('en-IN')}`

  // Icon styling based on type
  const iconBg = type === 'revenue'
    ? 'bg-blue-500/10 text-blue-600 dark:text-blue-400'
    : 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400'

  return (
    <Card className="overflow-hidden border border-border shadow-none hover:shadow-sm transition-all duration-200">
      <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
        <CardTitle className="text-[13px] font-medium text-muted-foreground tracking-tight">{title}</CardTitle>
        <div className={`p-2 rounded-lg ${iconBg}`}>
          <Icon className="h-4 w-4" />
        </div>
      </CardHeader>
      <CardContent>
        <div className={`text-2xl font-bold tracking-tight ${type === 'profit' && value > 0 ? 'text-emerald-600 dark:text-emerald-500' : 'text-foreground'}`}>
          {formattedValue}
        </div>
        <div className="flex items-center gap-1.5 mt-1">
          {!isNeutral && (
            isPositive ? (
              <TrendingUp className="h-3.5 w-3.5 text-emerald-500" />
            ) : (
              <TrendingDown className="h-3.5 w-3.5 text-rose-500" />
            )
          )}
          <span className={`text-[12px] font-medium ${isNeutral ? 'text-muted-foreground' : (isPositive ? 'text-emerald-500' : 'text-rose-500')
            }`}>
            {isNeutral ? 'No change' : `${isPositive ? '+' : ''}${change}%`}
          </span>
          <span className="text-[12px] hidden md:flex text-muted-foreground/70">from yesterday</span>
        </div>
      </CardContent>
    </Card>
  )
}

function RecentOrderItem({
  customer,
  amount,
  product,
  time,
  status,
}: {
  customer: string
  amount: string
  product: string
  time: string
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled'
}) {
  const statusConfig = {
    pending: { color: 'bg-yellow-500', label: 'Pending' },
    processing: { color: 'bg-blue-500', label: 'Processing' },
    shipped: { color: 'bg-purple-500', label: 'Shipped' },
    delivered: { color: 'bg-green-500', label: 'Delivered' },
    cancelled: { color: 'bg-red-500', label: 'Cancelled' },
  }

  return (
    <div className="flex items-start gap-3 pb-3 border-b last:border-0 last:pb-0">
      <div className={`h-2 w-2 rounded-full mt-2 ${statusConfig[status].color}`} />
      <div className="flex-1 space-y-1">
        <div className="flex items-start justify-between">
          <div>
            <p className="text-sm font-medium">{customer}</p>
            <p className="text-xs text-muted-foreground">{product}</p>
          </div>
          <p className="text-sm font-semibold">{amount}</p>
        </div>
        <p className="text-xs text-muted-foreground">{time}</p>
      </div>
    </div>
  )
}

function AlertItem({
  type,
  message,
  action,
  href,
}: {
  type: 'warning' | 'info' | 'success'
  message: string
  action: string
  href: string
}) {
  const config = {
    warning: { icon: AlertCircle, color: 'text-yellow-500' },
    info: { icon: AlertCircle, color: 'text-blue-500' },
    success: { icon: CheckCircle2, color: 'text-green-500' },
  }

  const Icon = config[type].icon

  return (
    <div className="flex items-start gap-3 p-3 rounded-lg border bg-card">
      <Icon className={`h-5 w-5 mt-0.5 ${config[type].color}`} />
      <div className="flex-1">
        <p className="text-sm">{message}</p>
        <Button variant="link" size="sm" className="h-auto p-0 mt-1" asChild>
          <Link href={href}>{action}</Link>
        </Button>
      </div>
    </div>
  )
}