import { NextRequest, NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { verifyEkodrixAuth } from '@/lib/ekodrix-auth'

export const dynamic = 'force-dynamic'

export async function GET(request: NextRequest) {
    try {
        // 🔒 SECURITY: Verify admin authentication
        await verifyEkodrixAuth()

        const supabase = await createAdminClient()
        const { searchParams } = new URL(request.url)

        const page = parseInt(searchParams.get('page') || '1')
        const limit = parseInt(searchParams.get('limit') || '10')
        const offset = (page - 1) * limit

        // Fetch recent enquiries (leads generated by platform users)
        const { data: enquiries, count, error } = await supabase
            .from('enquiries')
            .select(`
                *,
                reseller:profiles!user_id(full_name, business_name, email)
            `, { count: 'exact' })
            .order('created_at', { ascending: false })
            .range(offset, offset + limit - 1)

        if (error) throw error

        // Get some quick stats
        const { data: statsData } = await supabase
            .from('enquiries')
            .select('status')

        const stats = {
            total: statsData?.length || 0,
            pending: statsData?.filter(e => e.status === 'new').length || 0,
            converted: statsData?.filter(e => e.status === 'converted').length || 0,
        }

        return NextResponse.json({
            success: true,
            data: enquiries || [],
            summary: stats,
            pagination: {
                total: count || 0,
                page,
                limit,
                totalPages: Math.ceil((count || 0) / limit),
            }
        })
    } catch (error: any) {
        console.error('Ekodrix support API error:', error)
        return NextResponse.json(
            { success: false, error: error.message },
            { status: 500 }
        )
    }
}
